# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L8QR-bQ6sgAAQugKDg7xFvBp7JuA0C2J
"""

print("Hola, mundo!")
print("Hola, Mateo")