# Generated by Django 4.1.12 on 2023-10-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='correo@ejemplo.com', max_length=254, unique=True, verbose_name='Correo Electronico'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='nombre_de_usuario', max_length=100, unique=True, verbose_name='Nombre de usuario'),
        ),
    ]
