# Generated by Django 4.1.12 on 2023-10-31 01:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_direccion_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bibliografia',
            field=models.TextField(blank=True, verbose_name='Bibliografía'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='calificacion',
            field=models.DecimalField(decimal_places=1, default=3, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='incapacidad',
            field=models.CharField(choices=[('ninguna', 'Ninguna'), ('silla_de_ruedas', 'Silla de ruedas'), ('muletas', 'Muletas'), ('vision_reducida', 'Visión reducida')], default='ninguna', max_length=15, verbose_name='Incapacidad'),
        ),
    ]
