# Generated by Django 4.1.12 on 2023-11-20 02:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_bibliografia_usuario_calificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='calificacion',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación'),
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveIntegerField()),
                ('calificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_hechas', to=settings.AUTH_USER_MODEL)),
                ('usuario_calificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('calificador', 'usuario_calificado')},
            },
        ),
    ]
