# Generated by Django 4.1.12 on 2023-11-26 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_usuario_num_calificacionones'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='num_calificacionones',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='calificacion',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calificacion',
            name='calificado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calificado', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calificacion',
            name='categoria',
            field=models.CharField(choices=[('Manejo', 'Manejo'), ('Higiene', 'Higiene del vehiculo'), ('Charla', 'Buena Charla'), ('Puntualidad', 'Puntualidad'), ('General', 'General')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='promedio_charla',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='promedio_general',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='promedio_higiene',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='promedio_manejo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='promedio_puntualidad',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='calificador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='puntuacion',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='usuario_calificado',
        ),
    ]
