# Generated by Django 4.1.12 on 2023-11-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_calificacion_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='categoria',
            field=models.CharField(choices=[('Manejo', 'Manejo'), ('Higiene', 'Higiene del vehículo'), ('Charla', 'Buena Charla'), ('Puntualidad', 'Puntualidad'), ('General', 'General')], max_length=50),
        ),
    ]
