# Generated by Django 4.1.12 on 2023-10-29 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=100, verbose_name='Destino')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('condicion', models.CharField(choices=[('Activo', 'Activo'), ('A la espera de arranque', 'A la espera de arranque'), ('En curso', 'En curso'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Activo', max_length=23, verbose_name='Condición del Viaje')),
                ('puestos_maximos', models.IntegerField(default=1, verbose_name='Puestos Máximos')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes_conducidos', to=settings.AUTH_USER_MODEL)),
                ('pasajeros', models.ManyToManyField(blank=True, related_name='viajes_realizados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
