# Generated by Django 4.1.12 on 2023-11-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='discpacidades',
            field=models.CharField(choices=[('ninguna', 'Ninguna'), ('silla_de_ruedas', 'Silla de ruedas'), ('muletas', 'Muletas'), ('vision_reducida', 'Visión reducida')], default='ninguna', max_length=30, verbose_name='Discapacidades Aceptadas'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='inicio',
            field=models.CharField(default=(6.260699999606895, -75.57953881377448), max_length=200, verbose_name='Lugar de Partida'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='destino',
            field=models.CharField(max_length=200, verbose_name='Destino'),
        ),
    ]
