# Generated by Django 4.1.12 on 2023-11-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_rename_discpacidades_viaje_discapacidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='placa_vehiculo',
            field=models.CharField(default='XXXXXXX', max_length=20, verbose_name='Placa del Vehículo'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('Carro', 'Carro'), ('Moto', 'Moto')], default='Carro', max_length=50, verbose_name='Tipo de Vehículo'),
        ),
    ]
